"""initial schema

Revision ID: 48ae7286ef69
Revises: 
Create Date: 2026-06-14 19:16:55.473440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ae7286ef69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.String(length=32), nullable=False),
    sa.Column('last_seen', sa.String(length=32), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('resolve_votes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clusters_last_seen'), ['last_seen'], unique=False)

    op.create_table('moderation_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset', sa.String(length=24), nullable=False),
    sa.Column('event_publish_min', sa.Float(), nullable=False),
    sa.Column('event_discard_below', sa.Float(), nullable=False),
    sa.Column('manif_publish_min', sa.Float(), nullable=False),
    sa.Column('manif_discard_below', sa.Float(), nullable=False),
    sa.Column('always_review_blocking', sa.Integer(), nullable=False),
    sa.Column('always_review_offline', sa.Integer(), nullable=False),
    sa.Column('always_review_first_in_area', sa.Integer(), nullable=False),
    sa.Column('always_review_other', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('interaction_type', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('magnitude', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=False),
    sa.Column('photo_hash', sa.String(length=64), nullable=False),
    sa.Column('exif_json', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.String(length=32), nullable=False),
    sa.Column('capture_nonce_valid', sa.Integer(), nullable=False),
    sa.Column('veracity_score', sa.Float(), nullable=False),
    sa.Column('veracity_signals_json', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('cluster_id', sa.String(length=32), nullable=True),
    sa.Column('valid_from', sa.String(length=32), nullable=False),
    sa.Column('valid_to', sa.String(length=32), nullable=True),
    sa.Column('affected_edges_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_interaction_type'), ['interaction_type'], unique=False)
        batch_op.create_index('ix_reports_lat_lon', ['lat', 'lon'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_photo_hash'), ['photo_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index('ix_reports_status_validto', ['status', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_valid_to'), ['valid_to'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_valid_to'))
        batch_op.drop_index('ix_reports_status_validto')
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_priority'))
        batch_op.drop_index(batch_op.f('ix_reports_photo_hash'))
        batch_op.drop_index('ix_reports_lat_lon')
        batch_op.drop_index(batch_op.f('ix_reports_interaction_type'))
        batch_op.drop_index(batch_op.f('ix_reports_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_reports_category'))

    op.drop_table('reports')
    op.drop_table('moderation_policy')
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_last_seen'))
        batch_op.drop_index(batch_op.f('ix_clusters_category'))

    op.drop_table('clusters')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
